// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fttdjnogpshbqgryvcar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0dGRqbm9ncHNoYnFncnl2Y2FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NDc5MDQsImV4cCI6MjA2NjIyMzkwNH0.eChdVMH7mG_Gf_2Hf-PiwYaB8MRwDiLA62i6jdQzOWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);